package com.nexion.process.backend.entity;

public class WordPlaceSample {

    public static String[] FUENTE = {"FUENTES","AGUA CRUDA","CRUDA","POZO","POZOS","BOCA","FUENTE","REPRESA","RIO","RÍO","LAGUNA","CARCAMO","BOCA DE POZO"};
    public static String[] TANQUE = {"TANQUE","COLA","ELEVADO","SEMIENTERRADO","SEMI-ENTERRADO","ENTERRADO","SEMI ENTERRADO","AGUA DISTRIBUIDA DEL TANQUE",
    "SALIDA","SALIDA PLANTA","TRATAMIENTO","PLANTA","ELEVADO","ALMACENAMIENTO","TANQUE DE ALMACENAMIENTO SEMI-ENTERRADO","PLANTA TRATAMIENTO"};
    public static String[] RED ={"RED", ": RED DE DISTRIBUCION","GRIFO","DOMICILIARIA","AD","AGUA DISTRIBUIDA DEL POZO", "DOMICILIARIO","PILETA","CODIGO",
     "CÓDIGO","USUARIO","PF","PUNTO FIJO","PV","PUNTO VARIABLE","AGUA DISTRIBUIDA","DISTRIBUIDA","AGUA DISTSRIBUIDA","AGUA POTABLE","POTABLE"};
}
